name: nf-core CI
# This workflow runs the pipeline with the minimal test dataset to check that it completes without any syntax errors
on:
  push:
    branches:
      - dev
  pull_request:
  release:
    types: [published]

env:
  NXF_ANSI_LOG: false

jobs:
  test:
    name: ${{ matrix.test }} (${{ matrix.profile }}-${{ matrix.NXF_VER }})
    # Only run on push if this is the nf-core dev branch (merged PRs)
    if: "${{ github.event_name != 'push' || (github.event_name == 'push' && github.repository == 'nf-core/rnaseq') }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        NXF_VER:
          - "21.10.3"
          - "latest-everything"
        test:
          - "Run default pipeline with test data"
          - "Test STAR Salmon with skip_qc workflow parameters"
          - "Test STAR Salmon with skim_trimming workflow parameters"
          - "Test STAR Salmon with gtf false workflow parameters"
          - "Test STAR Salmon with star_index false workflow parameters"
          - "Test STAR Salmon with transcript_fasta false workflow parameters"
          - "Test STAR Salmon with min_mapped_reads 90 workflow parameters"
          - "Test STAR Salmon with with_umi workflow parameters"
          - "Test STAR Salmon with with_umi skip_trimming workflow parameters"
          - "Test STAR Salmon with remove_ribo_rna and skip_qualimap workflow parameters"
          - "Test STAR Salmon with bam_csi_index workflow parameters"
          - "Test STAR Salmon with save_align_intermeds save_reference workflow parameters"
          - "Test STAR Salmon with featurecounts_group_type false workflow parameters"
          - "Test STAR RSEM with skip_qc workflow parameters"
          - "Test STAR RSEM with rsem_index false workflow parameters"
          - "Test HISAT2 with skip_qc workflow parameters"
          - "Test HISAT2 with hisat2_index false workflow parameters"
          - "Test Salmon with skip_qc skip_alignment workflow parameters"
          - "Test Salmon with salmon_index false transcript_fasta false workflow parameters"
        profile: ["docker", "singularity", "conda"]
        exclude:
          - NXF_VER: "latest-everything"
            profile: "conda"
    steps:
      - name: Check out pipeline code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python dependencies
        run: python -m pip install --upgrade pip pytest-workflow

      - uses: actions/cache@v2
        with:
          path: /usr/local/bin/nextflow
          key: ${{ runner.os }}
          restore-keys: |
            ${{ runner.os }}-nextflow-

      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v1
        with:
          version: "${{ matrix.NXF_VER }}"

      - name: Set up Singularity
        if: matrix.profile == 'singularity'
        uses: eWaterCycle/setup-singularity@v5
        with:
          singularity-version: 3.7.1

      - name: Set up miniconda
        if: matrix.profile == 'conda'
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          channels: conda-forge,bioconda,defaults
          python-version: ${{ matrix.python-version }}

      - name: Conda clean
        if: matrix.profile == 'conda'
        run: conda clean -a

      - name: Run pipeline with tests settings
        run: TMPDIR=~ PROFILE=${{ matrix.profile }} pytest --tag "${{ matrix.test }}" --symlink --kwdof --git-aware --color=yes

      - name: Output log on failure
        if: failure()
        run: |
          sudo apt install bat > /dev/null
          batcat --decorations=always --color=always /tmp/pytest_workflow_*/*/log.{out,err}

      - name: Upload logs on failure
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: logs-${{ matrix.profile }}
          path: |
            /tmp/pytest_workflow_*/*/.nextflow.log
            /tmp/pytest_workflow_*/*/log.out
            /tmp/pytest_workflow_*/*/log.err
            /tmp/pytest_workflow_*/*/work
            /tmp/pytest_workflow_*/**/.command.log
            !/tmp/pytest_workflow_*/*/work/conda
            !/tmp/pytest_workflow_*/*/work/singularity
